=== Dylar/qcar-repo/apps/qcar-customer/assets/schema/car_info_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "brand": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "imagePath": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {}
    }
  },
  "required": [
    "brand",
    "model",
    "imagePath"
  ]
}

=== Dylar/qcar-repo/testdata/customer/car_info_full.json
{
  "brand": "Toyota",
  "model": "CorollaTSGR",
  "imagePath": "Path/to/image.jpg",
  "categories": [
    {
      "name": "Sicherheit",
      "order": 1,
      "description": "Hier geht alles um Sicherheit",
      "imagePath": "Path/to/image.jpg",
      "videos": [
        {
          "brand": "Toyota",
          "model": "CorollaTSGR",
          "filePath": "2-Zonen Klimaautomatik.mp4",
          "imagePath": "2-Zonen Klimaautomatik.jpg",
          "name": "2-Zonen Klimaautomatik",
          "description": "Für gute Luft, sorgt die Klimaautomatik.",
          "tags": [
            "Luft",
            "Zone",
            "Klima",
            "Automatisch",
            "Scheibe",
            "2"
          ]
        },
        {
          "brand": "Toyota",
          "model": "CorollaTSGR",
          "filePath": "3-Zonen Klimaautomatik.mp4",
          "imagePath": "3-Zonen Klimaautomatik.jpg",
          "name": "3-Zonen Klimaautomatik",
          "description": "Für gute Luft, sorgt die Klimaautomatik.",
          "tags": [
            "Erde",
            "DDR",
            "Solo",
            "Manuel",
            "Dreieck",
            "3"
          ]
        }
      ]
    },
    {
      "name": "Komfort",
      "order": 1,
      "description": "Hier geht alles um Sicherheit",
      "imagePath": "Path/to/image.jpg",
      "videos": [
        {
          "brand": "Toyota",
          "model": "CorollaTSGR",
          "filePath": "4-Zonen Klimaautomatik.mp4",
          "imagePath": "4-Zonen Klimaautomatik.jpg",
          "name": "4-Zonen Klimaautomatik",
          "description": "Für gute Luft, sorgt die Klimaautomatik.",
          "tags": [
            "Luft",
            "Zone",
            "Klima",
            "Automatisch",
            "Scheibe",
            "2"
          ]
        }
      ]
    }
  ]
}
