=== Dylar/qcar-repo/apps/qcar-customer/assets/schema/video_info_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "brand": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "filePath": {
      "type": "string"
    },
    "imagePath": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "brand",
    "model",
    "category",
    "filePath",
    "imagePath",
    "name",
    "description",
    "tags"
  ]
}

=== Dylar/qcar-repo/apps/qcar-customer/test/testdata/video_info.json
{
  "brand": "Toyota",
  "model": "Corolla",
  "category": "Komfort",
  "filePath": "2-Zonen Klimaautomatik.mp4",
  "imagePath": "2-Zonen Klimaautomatik.jpg",
  "name": "2-Zonen Klimaautomatik",
  "description": "FÃ¼r gute Luft, sorgt die Klimaautomatik.",
  "tags": [
    "Luft", "Zone", "Klima", "Automatisch", "Scheibe", "2"
  ]
}

=== Dylar/qcar-repo/testdata/customer/video_info.json
{
  "brand": "Toyota",
  "model": "CorollaTSGR",
  "category": "Sicherheit",
  "filePath": "Motorhaube entriegelung.mp4",
  "imagePath": "Motorhaube entriegelung.jpg",
  "name": "Motorhaube entriegelung",
  "description": "FÃ¼r gute Luft, sorgt die Klimaautomatik.",
  "tags": [
    "Luft", "Zone", "Klima", "Automatisch", "Scheibe", "2"
  ]
}
